name: UI Tests

on:
  push:
    branches:
      -main
jobs:
  test:
    name: Запуск тестов
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: setup-node/setup-node@v4
       with:
         node-version: '20'
     - run: npm ci 
     - run: npm run test:chrome